version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t pn-server:latest .
      - docker tag pn-server:latest 017359606234.dkr.ecr.us-east-1.amazonaws.com/pn-server:latest
  post_build:
    commands:
      - docker push 017359606234.dkr.ecr.us-east-1.amazonaws.com/pn-server:latest
      - printf '[{"name":"petServer","imageUri":"%s"}]' 017359606234.dkr.ecr.us-east-1.amazonaws.com/pn-server:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json